:page-layout: general-reference
:page-doc-category: Getting Started
:page-title: Using Kabanero Collections in Codewind
:linkattrs:
= Using Kabanero Collections in Codewind

== Prerequisites
* https://eclipse.com/codewind[Codewind for VS Code or Eclipse v0.3.0 or later]
* https://www.docker.com/get-started[Docker]
* https://appsody.dev/docs/getting-started/installation[Appsody]
* https://github.com/eclipse/codewind-appsody-extension[Appsody Extension for Codewind v0.3.0 or later]
** Follow the instructions `Installing the Appsody Extension on Codewind` and `Optional: Using the Same Appsody Configuration Between Local CLI and Codewind` in the README.md file


== Replace the default templates with the Kabanero Collections templates
Now that your local Appsody CLI points to the Appsody Extension, you can modify the repo's with the standard repo commands. 

. First you will need to add the https://github.com/kabanero-io/collections[Kabanero Collections Repository]:
+
`appsody repo add kabanero https://github.com/kabanero-io/collections/releases/download/v0.1.0/kabanero-index.yaml`

. Set the Kabanero Collections repo to default so you can remove the old default templates:
+
`appsody repo set-default kabanero`

. Remove the default templates:
+
----
appsody repo remove appsodyhub
appsody repo remove experimental
----

== Create a project from a Kabanero Collection
Once the Kabanero templates have been added, you can create a project like you normally would in Codewind.

* VS Code 
** Open  up the Command Palette and search for: "Codewind: Create New Project". 

* Eclipse 
** Create a new project from the Codewind Explorer window
*** Projects that start with `Appsody` are from the Kabanero collection.