== Using Kabanero Collections in Codewind

=== Prerequisties
* eclipse.com/codewind[Codewind for VS Code or Eclipse]
* https://www.docker.com/get-started[Docker]
* https://appsody.dev/docs/getting-started/installation[Appsody]
* github.com/eclipse/codewind-appsody-extension[Appsody Extension for Codewind]
** Follow the instructions `Installing the Appsody Extension on Codewind` and `Optional: Using the Same Appsody Configuration Between Local CLI and Codewind` in the README.md


=== Replacing the Default Templates with the Kabanero Collection Templates
Now that your local Appsody CLI points to the Appsody Extension, you can modify the repo's with the standard repo commands. 

First you will need to add the Kabanero Collection Repo: 
* `appsody repo add kabanero https://github.com/kabanero-io/collections/releases/download/v0.1.0/kabanero-index.yaml`

Then you want to set it to default so you can remove the old default templates: 
* 'appsody repo set-default kabanero`

Then you can remove the default templates:
* `appsody repo remove appsodyhub`
* `appsody repo remove experimental`


=== Create a Project from the Kabanero Collection
Once the Kabanero templates have been added you can create a project like any you normally would in Codewind.
* In VS Code you can do this by opening up the Command Palette and searching for "Codewind: Create New Project". 
* In Eclipse you can create a new project from the Codewind Explorer window. 

The projects that start with `Appsody` are from the Kabanero collection.

