:page-layout: doc
:page-doc-category: Reference
:page-title: Working with Collections in VS Code or Eclipse
:linkattrs:
:sectanchors:

= Working with Kabanero Collections in VS Code or Eclipse

== Prerequisites
* https://www.docker.com/get-started[Docker]
* https://eclipse.com/codewind[Codewind for VS Code or Eclipse v0.3.0 or later]
* (Optional) If you have an enterprise-specific Kabanero Collection Hub, you need the URL to your index file.


== Configuring your environment to use a Kabanero Collection Hub

To configure your development environment to use a Kabanero Collection, you must enable the repository as a source for templates.
As a developer, your enterprise architect might provide you with the URL of a Kabanero Collection Hub that your organisation has
defined for developers to use. In this case, you can configure Codewind to point to the templates in this Collection Hub.
If you haven’t been given a URL for your organisation, you should clone the public Kabanero Collection Hub locally and configure
Codewind to use the templates from that repository instead.

To enable a Kabanero Collection Hub repository, open the **Manage Template Sources** view in your IDE by right-clicking
on **Projects(local)**. When the view opens, click the **Add New** button and enter the URL for the Kabanero Collection
Hub repository in the pop-up field. For example, the following URL points to the public Kabanero Collection Hub repository
for version 0.3.0:

----
https://github.com/kabanero-io/collections/releases/download/0.3.0/kabanero-index.json
----

Use your local Kabanero Collection Hub repository instead.

If any template sources other than Kabanero are enabled, click on the switches to deselect them; these Collections are not
supported by the Kabanero application cluster.

== Create a project from a Kabanero Collection

When you've added the Kabanero templates, you're ready to create a new project.

* VS Code
** Open up the Command Palette and search for: "Codewind: Create New Project".

* Eclipse
** Create a new project from the Codewind Explorer window.

Choose from the available Kabanero templates to create your first microservice application!
