:page-layout: doc
:page-doc-category: Reference
:page-title: Modifying the default Kabanero collections
:linkattrs:
:sectanchors:
= Modifying the default Kabanero collections

The default collections can be modified to suit the needs of your organization.  Use the following steps to customize the default collections and store them in a new Github repository:

. Clone the default collections repository and create a new copy of it in your Github organization.  In this example, we are referring to `github.example.com` as the remote Github repository, and we refer to it locally as `private-org`.
+
----
git clone https://github.com/kabanero-io/collections.git
cd collections
git remote add private-org https://github.example.com/my_org/collections.git
git push -u private-org
----
+
Once this has been done, you will have your own copy of the collections repository in your own Github org/repo. Follow any normal development processes you have for using git (i.e., creating branches, etc.).

. Create or modify the collections if required.
* You can find out more about https://github.com/appsody/website/blob/master/content/docs/stacks/create.md[creating or modifying collections, window="_blank"].

. Set up local build environment.

There are several tools that are used to build.:::
* yq
** Command-line YAML processor  (sudo snap install yq)
* docker
** A tool to help you build and run apps within containers

These are only required if you are also building the Codewind Index (export CODEWIND_INDEX=true):::

* python3
** Python is a general-purpose interpreted, interactive, object-oriented, and high-level programming language
* pyyaml
** YAML parser and emitter for python (pip3 install pyyaml)

. There are several environment variables that need to be set up. These are required in order to correctly build the collections.
+
----
# Organization for images
export IMAGE_REGISTRY_ORG=kabanero

# Whether to build the Codewind Index file
export CODEWIND_INDEX=false
----
+
These settings are also required to correctly release the collections (if done manually):
+
----
# Publish images to image registry
export IMAGE_REGISTRY_PUBLISH=false

# Credentials for publishing images:
export IMAGE_REGISTRY=<registry>
export IMAGE_REGISTRY_USERNAME=<registry_username>
export IMAGE_REGISTRY_PASSWORD=<registry_password>
----

. Build collections.
+
From the base directory, run the build script.  For example:
+
----
. ./ci/build.sh
----
+
Note that this will build all the collections in the incubator directory.
+
Following the build, you can find the generated collection assets in the `file://$PWD/ci/assets/` directory and all the docker images in your local docker registry.

. Test the collections locally using Appsody.
+
To test the collections, add the `kabanero-index.yaml` to Appsody using the Appsody CLI:
+
----
appsody repo add kabanero file://$PWD/ci/assets/kabanero-index-local.yaml
----
+
This will enable you to do an `appsody init` for a collection that is in the newly built kabanero collections.  For example:
+
----
appsody init kabanero/java-microprofile
----

. Push changes back to your repository:
* Once you have made all the changes to the collection and you are ready to push the changes back to your git repository then
+
----
# Commit your changes back to git
git commit -a -m "Updates to the collections"

# Push the changes to your repository.   For example:
git push -u private-org
----
+
If Travis CI has been setup in your git organization, the push to git should trigger the Travis build to run, which will ensure that the changes build OK.

. Release the final version of the collections.
* Once all changes have been made to the Collections and they are ready to be released, if a full release of the collections is required, create a git tag:
+
----
git tag "v0.1.1 -m "Collections v0.1.1"
# push the tags to git:
git push --tags
----
+
This will trigger another Travis build that will also generate a Git Release and push the images to the image repository.

. Test the pipelines and other components that have been included in the collection link:collection-install.html[within the Kabanero/OpenShift environment].

. Declare the release final.  If you need to make additional changes, repeat the process using the same repository you created in the first step, and create a new tag to represent a new release.

== Need help?
If you have questions, we would like to hear from you.
You can reach out to the community for assistance on the https://ibm-cloud-tech.slack.com/messages/CJZCYTD0Q[Kabanero Slack channel, window="_blank"].
