:page-layout: general-reference
:page-type: general
:page-title: Appsody Hello World on Codewind
:linkattrs:
= Appsody Hello World on Codewind

== Prerequisites
. https://www.eclipse.org/codewind/installlocally.html[Codewind] on Visual Studio Code or Eclipse
. https://appsody.dev/docs/getting-started/installation[Appsody]
. https://github.com/kabanero-io/appsodyExtension[Appsody Extension for Codewind]

== Getting started with VS Code

=== Creating a Java Springboot appsody Project
In VS Code open the command palette and navigate to the option `Codewind: Create New Project`. 
Select the Appsody Java Springboot 2 template, give it a name and press enter. Navigate to the `Explorer` view. 
In the `Explorer` view keep expanding the Codewind section until the project you created is visible. 
At this point you can click the box with arrow icon next to the project to open it up in a browser, or the information icon to view the project overview.

Opening up the project in a web browser will direct you to a landing Hello World page. The page contains a list of other built in APIs that you can test out as well.

*NOTE:* The project might still be `starting` and you'll need to wait for it to be running.

== Getting started with Eclispe

=== Creating a Java MicroProfile appsody Project
Open up the Codwind Explorer in your Eclipse workspace by clicking `Window -> Show View -> Other... -> Codewind -> Codewind Explorer`.
Right click on the `Local Projects` under `Codewind` and select `New Project`. Select the Appsody Java MicroProfile template, give it a name and create it.
Now underneath your `Codewind -> Local Projects`, there should be your project. 
You can right click on the project and "Open Application" to view your app in your browser.

Opening up the project in a web browser will direct you to a landing Hello World page. The page contains a list of other built in APIs that you can test out as well.

*NOTE:* The project might still be `starting` and you'll need to wait for it to be running. Also you might need to refresh the project explorer to see the contents of your project directory.

== Hello World

=== Edit the index.html
Right-click on the appsody project and chose the option to `Open Folder as Workspace`. In the project workspace, navigate to `src/main/resources/public` and create open the file called `index.html`.
Open the file and add edit the text. Save the file, open the project information, and build the project again. 
Open the project in your web browser again and the webpage will now be displaying your change. 
