= appsody Hello World on Codewind

== Prerequisites
. https://www.eclipse.org/codewind/installlocally.html[Codewind] on Visual Studio Code 
. https://appsody.dev/docs/getting-started/installation[Appsody]
. https://github.com/kabanero-io/appsodyExtension[Appsody Extension for Codewind]

== Getting started

=== Creating a Java MicroProfile appsody Project
In VS Code open the command palette and navigate to the option `Codewind: Create New Project`. 
Select the Appsody Java MicroProfile template, give it a name and press enter. Navigate to the `Explorer` view. 
In the `Explorer` view keep expanding the Codewind section until the project you created is visible. 
At this point you can click the box with arrow icon next to the project to open it up in a browser, or the information icon to view the project overview.
The base url that you will be directed to doesn't have any information yet. However appending `/health` will display the health of the container.
Other built in endpoints are described on the bottom of the https://github.com/appsody/stacks/blob/master/incubator/java-microprofile/README.md[application stack's README] 

*NOTE:* The project might still be `starting` and you'll need to wait for it to be running.

== Hello World

=== Create the index.html
Right-click on the appsody project and chose the option to `Open Folder as Workspace`. In the project workspace, navigate to `src/webapp/` and create a new file there called `index.html`.
Open the file and add `Hello World`. Save the file and click the icon to open the app in your web browser again. You should see a webpage with `Hello World`. Now you can go back to the file and change it, save it, and then refresh the webpage.
The webpage will now be displaying your change. 

While this is only a basic Hello World html file, this same process goes for any changes in the project you want to make.
