:page-layout: doc
:page-doc-category: Reference
:linkattrs:
:sectanchors:
= Troubleshooting: Collecting MustGather data for Kabanero

You can use the `mustgather` command to collect data about your environment.  This information can be useful in troubleshooting and fixing problems.

There are several mustgather scripts available:
  * appsody-mustgather.sh
  * che-mustgather.sh
  * istio-mustgather.sh
  * kabanero-mustgather.sh
  * kappnav-mustgather.sh
  * knative-mustgather.sh
  * mustgather-all.sh
  * tekton-mustgather.sh

To run a `mustgather` script:

1. In a terminal session, navigate to the location where you cloned the kabanero-foundation repository.

2. Log in to your cluster.

  ```bash
  oc login https://<your_cluster_hostname> -u <username> -p <password>
  ```

3. Run a `mustgather` command.

For example:
  ```bash
  mustgather-all.sh
  ```

  **Tip**: You can set the environment variable `LOGS_DIR` to specify the data output location:
  ```bash
  LOGS_DIR=<my_directory> ./mustgather-all.sh
  ```
  {:tip}

  By default, MustGather data is stored in the `kabanero-debug` directory. The command also stores compressed information in the `kabaner-debug-<timestamp>.tar.gz` file.
