:page-layout: doc
:page-doc-category: Installation
:page-title: Installing and upgrading Kabanero Foundation
:linkattrs:
:sectanchors:

Today, Kabanero has been tested on the Origin Community Distribution of Kubernetes(OKD) version 3.11. There is intent to also expand testing on additional distributions including upstream Kubernetes in the future.

== Prerequisites

* Kubernetes is installed
* openshift_master_default_subdomain is configured
** See https://docs.okd.io/3.11/install/configuring_inventory_file.html[Configuring Your Inventory File, window="_blank"]
* Wildcard DNS is available for your subdomain
** alternatively, nip.io can be used
* The Internal Registry is configured
** See more about the https://docs.okd.io/3.11/install_config/registry/index.html[Internal Registry, window="_blank"]

== Installation

. In a terminal session, create and `cd` to a temporary working directory of your choice.

. Retrieve the https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts[installation scripts from our kabanero-foundation repository, window="_blank"]
* Clone the repository to get the scripts `git clone https://github.com/kabanero-io/kabanero-foundation.git`
* ... or, download the repository as a zip file `https://github.com/kabanero-io/kabanero-foundation/archive/master.zip`

. Navigate to the **scripts** directory: `cd kabanero-foundation/scripts`

. Ensure you are logged into your cluster with the https://docs.openshift.com/container-platform/3.11/cli_reference/get_started_cli.html#basic-setup-and-login[`oc login` command]

. Review the `install-kabanero-foundation.sh` script for any optional components that can be enabled by setting the required environment variable, or by editing the value in the script directly.  Optional components are listed at the top of the script, below the section titled `Optional components`.

. As a `cluster-admin`, run the following:
* Don't forget to replace `<MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN>` with your subdomain, and do not include the angle brackets:
* `openshift_master_default_subdomain=<MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN> ./install-kabanero-foundation.sh`
* If using a wildcard DNS such as nip.io, append it to the subdomain: `openshift_master_default_subdomain=<MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN>.nip.io ./install-kabanero-foundation.sh`
* If installing the optional kAppNav component, specify `yes` on the ENABLE_KAPPNAV environment variable.  If not, specify `no`.
* For example: `ENABLE_KAPPNAV=yes openshift_master_default_subdomain=9.9.9.9.nip.io ./install-kabanero-foundation.sh`

. Create a `Kabanero` custom resource (CR) instance.
* A sample `oc apply` command which applies the default instance for this release of Kabanero, including the default collections, is printed at the conclusion of the `install-kabanero-foundation.sh` script.  The CR instance can be modified to include the URL of a custom collection and the Github information necessary to administer that collection.
* For more information on customizing the CR instance, see link:kabanero-cr-config.html[the Kabanero CR configuration reference].

== After Install

The **Kabanero Landing Page** is installed as part of the install process and is a good next step to go explore information about your Kabanero instance.

=== View the Landing Page
. In your OKD Console
.. Click on the **Kabanero** tab on the left hand navigation.

**Note**: If you do not see the **Kabanero** tab, proper certificates might not be installed in your cluster. You will have to accept the self-signed certificate before the **Kabanero** tab is displayed.
To accept the self signed certificate you will have to **go to the landing page URL in your browser and accept the self-signed certificate**.

There are two ways to get the landing page URL::

Using the `oc` CLI:::
. Open a terminal and run: `oc get routes -n kabanero`
. Find the result with the name `kabanero-landing`. The URL is displayed under **HOST/PORT** for that row.

Using the OKD Console:::
. Switch the project to **kabanero**
. Under **Applications** click **Routes**
. The landing page name is **kabanero-landing** which should be in the list of routes. Click the URL under **Hostname** to open the landing application

If the landing page is not responding:::
. It might take some time for the landing page and other pods to be created and started. You can check the status of the Kabanero pods with `oc get pods -n kabanero`. Wait until they all have a status of *Running*.
+
```
# oc get pods -n kabanero
NAME                                                        READY     STATUS    RESTARTS   AGE
appsody-operator-79ccd57895-9lsmt                           1/1       Running   0          11m
controller-manager-0                                        1/1       Running   4          29m
kabanero-cli-855c64f6fc-j6s44                               1/1       Running   0          11m
kabanero-landing-6dc5c798d4-ncg52                           1/1       Running   0          11m
kabanero-operator-68877b5d6b-6wqr4                          1/1       Running   1          29m
knative-eventing-operator-67cdf5dc9f-fhzbt                  1/1       Running   0          29m
knative-serving-operator-b64558bbc-k5sjl                    1/1       Running   0          29m
openshift-pipelines-operator-66c4d787cf-7kjjk               1/1       Running   0          29m
tekton-dashboard-55fd66fbff-2bzhl                           2/2       Running   0          27m
webhooks-extension-65d44777-tsz4j                           1/1       Running   0          27m
webhooks-extension-sink-4wq7k-deployment-6c9cd554f5-gf7rk   2/2       Running   0          26m
```

== Upgrade

. Navigate to the cloned `kabanero-foundation` repository that was used to install Kabanero.  Make sure the repository is current:  `git pull`

. Check out the release that you want to upgrade to.  A list of releases can be found link:https://github.com/kabanero-io/kabanero-foundation/releases[on the kabanero-foundation Github repository].  For example, `git checkout 0.2.0`

. To upgrade from release to release, use the `upgrade-kabanero-foundation.sh`
script.  Set environment variable KABANERO_BRANCH to be the kabanero-operator release that you want to upgrade to.  If you checked out `kabanero-foundation` to a tagged release in the previous step, this variable will by default be the correct value.  The script will update the Kabanero operator to the desired release.  For example:
+
```
KABANERO_BRANCH=0.2.0 ./upgrade-kabanero-foundation.sh
```

. After the script completes successfully, update your Kabanero CR
instances to use the new version.  If you are using the default collection set,
consider updating it to the new version as well.  For an example, see link:https://raw.githubusercontent.com/kabanero-io/kabanero-operator/master/config/samples/default.yaml[default.yaml], which sets the version, and uses the default collection set.

== Optional sample - Appsody project with manual Tekton pipeline run

. Create a Persistent Volume for the pipeline to use. A sample hostPath `pv.yaml` is provided.
* `oc apply -f pv.yaml`

. Create the pipeline and execute the example manual pipeline run
* `APP_REPO=https://github.com/dacleyra/appsody-hello-world/ ./appsody-tekton-example-manual-run.sh`

. By default, the application container image will be built and pushed to the Internal Registry, and then deployed as a Knative Service.
* Access the application at: `http://appsody-hello-world.appsody-project.<MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN>`

. Optional - Access the pipeline logs
* `oc logs $(oc get pods -l tekton.dev/pipelineRun=manual-pipeline-run --output=jsonpath={.items[0].metadata.name}) --all-containers`

. Optional - Make detailed pipeline changes by accessing the Tekton dashboard
* `http://tekton-dashboard.<MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN>`
