:page-layout: doc
:page-doc-category: Installation
:page-title: Installing Codewind in VS Code or Eclipse
:linkattrs:
:sectanchors:
Eclipse Codewind enables you to develop microservice applications from Kabanero Collections in an IDE. Follow one of these
links for your chosen IDE:

- link:installing-dev-tools.html#installing-codewind-for-vs-code[Installing Codewind for VS Code]
- link:installing-dev-tools.html#installing-codewind-for-eclipse[Installing Codewind for Eclipse]

== Installing Codewind for VS Code
The Codewind installation includes two steps:

. The VS Code extension installs when you install Codewind from the VS Code Marketplace or when you install by searching in the "VS Code Extensions" view.
. The Codewind back end containers install after you click "Install" when you are prompted. After you click Install, the necessary images are downloaded from the internet. The download is approximately 1 GB.

The following Codewind images are pulled. These images together form the Codewind back end:

* `eclipse/codewind-initialize-amd64`
* `eclipse/codewind-performance-amd64`
* `eclipse/codewind-pfe-amd64`

When the installation is complete, the extension is ready to use. For more information, see https://www.eclipse.org/codewind/mdt-vsc-getting-started.html[Getting started: Codewind for VS Code, window="_blank"].

To get started with Kabanero Collections in VS Code, see link:codewind-kabanero-collections.html[Working with Collections in VS Code or Eclipse]


=== Updating the Codewind plug-in
Update your Codewind plug-in without unintalling the extension.

. Go to the *Extensions* view in VS Code
. Search for the latest Codewind version in the Marketplace
. Install the latest version of Codewind. Then, reload Codewind
. Go to the *Explorer* view in VS Code
. Depending on the current status of Codewind, one of two messages appear:
* If the images from a previous version or release of Codewind are installed on the system, but Codewind is not running, a message asks you to install the most recent images. Click *OK* to start the download
* If an older version of Codewind is installed and running, a message asks you to update the older version. Click *OK,* and Codewind stops automatically, and new images begin to download
. Wait for the Codewind installation to complete. Codewind starts and is ready to use

=== Removing containers and images
To remove Codewind, see https://www.eclipse.org/codewind/mdt-vsc-uninstall.html[Uninstalling Codewind from VS Code, window="_blank"].

=== Troubleshooting

* Reinitiating the Codewind installation
** If you don't click "Install" when the notification window first appears, you can access the notification again.
Go to *View > Explorer*, then click *Codewind* and hover the cursor over "Codewind" where there is a switch to turn Codewind on or off.  Click the switch so that it is on. The notification window is displayed.

* Resetting the installation
** To reset the installation, uninstall Codewind and install it again.

For more information about troubleshooting Codewind, see the https://www.eclipse.org/codewind/troubleshooting.html[Codewind Troubleshooting page, window="_blank"].

'''

== Installing Codewind for Eclipse
The Codewind installation includes two steps and 1 optional step:

. The Eclipse plug-in installs when you install Codewind from the Eclipse Marketplace or when you install by searching in the "Eclipse Extensions" view.
. The Codewind back end containers install after you click "Install" when you are prompted. After you click "Install," the necessary images are downloaded from the internet. The download is approximately 1 GB.
. *Optional*: If you don't click "Install" when the notification window first appears, you can access the notification again.
Go to *View > Explorer*, then click *Codewind* and hover the cursor over "Codewind" where there is a switch to turn Codewind on or off.  Click the switch so that it is on. The notification window is displayed.

The following images are pulled. These images together form the Codewind back end:

* `eclipse/codewind-initialize-amd64`
* `eclipse/codewind-performance-amd64`
* `eclipse/codewind-pfe-amd64`

When the installation is complete, the extension is ready to use, and you are prompted to open the Codewind workspace.
You can open the Codewind workspace or a project within the workspace as your Eclipse workspace. For more information,
see https://www.eclipse.org/codewind/mdteclipsegettingstarted.html[Getting started: Codewind for Eclipse, window="_blank"]

* On macOS and Linux, the workspace folder is `~/codewind-workspace`.
* On Windows, the workspace folder is `C:\codewind-workspace`.

When Codewind creates a new project, it is created in the Codewind workspace. If you want to add an existing project to Codewind, first copy it into the Codewind workspace.

To get started with Kabanero Collections in your Eclipse IDE, see link:codewind-kabanero-collections.html[Working with Collections in VS Code or Eclipse]

=== Updating the Codewind plug-in
Update the Codewind Eclipse plug-in to the latest version.

. From Eclipse, go to *Help > About Eclipse IDE*
. Click *Installation details*
. To look for the latest release, highlight`Codewind tech preview` and click *Update....*
. Select the latest version and click *Next*
. Review the license and click *Finish*
. Click *Restart Now* to refresh Codewind to the latest version
. After Codewind restarts, go to the *Codewind Explorer* view and double-click *Codewind* to update it to the latest version
. Click *OK* in the *Codewind Update* window that states that the older version of Codewind will be removed, and the newer version will be started
. After Codewind updates, the *Codewind Explorer* view appears with your projects

=== Removing containers and images
To remove Codewind, see https://www.eclipse.org/codewind/mdteclipseuninstall.html[Uninstalling Codewind from Eclipse, window="_blank"].

=== Troubleshooting
To troubleshoot Codewind, see the https://www.eclipse.org/codewind/troubleshooting.html[Codewind Troubleshooting page, window="_blank"].
