:page-layout: doc
:page-type: doc
:page-title: Kabanero CLI
:page-doc-category: Getting Started
:linkattrs:
:sectanchors:
= Kabanero CLI

Kabanero CLI is a command-line interface for managing collections and onboarding developers in a Kabanero environment. This interface is used by the enterprise, solution, or application architect who defines and manages the Kabanero collections that are used by developers to create governed applications.

== Kabanero commands

Use the following commands to monitor and administer a Kabanero environment.


=== Log in to Kabanero

Run the `kabanero login` command to authenticate to Kabanero.

-----
kabanero login userid Github-PAT|Github-password kabanero-url
-----

Log in to a Kabanero instance by using GitHub credentials and store a temporary access token for subsequent command-line calls.
The temporary access token is stored in a `your-home-directory/.kabanero/config.yaml` file.
Use your GitHub user ID and either a password or Personal Access Token (PAT) to log in.

Examples:

-----
# login with GitHub userid and password:
kabanero login my.kabaneroInstance.io -u myGithubID -p myGithubPassword

# login with previously used url Github userid and PAT:
	kabanero login -u myGithubID -p myGithubPAT
-----

=== Onboard a developer

Run the `kabanero onboard` command to onboard a developer to the Kabanero environment.

-----
kabanero onboard github-id repo-name
-----

This command is under development. Once integrated, it sends an email to the specified user that provides the necessary information to get started with Kabanero.

=== List Kabanero collections

Run the `kabanero list` command to list all the collections in a kabanero instance, along with their status.

-----
kabanero list
-----

=== Refresh collections

Run the `kabanero refresh` command to refresh the list of collections from master, making these collections current with the activated collections across all namespaces in the Kabanero instance. This command can also be used to restore deactivated collections. See <<Deactivate Kabanero>>.

----
kabanero refresh
----

=== Show the Kabanero version

Run the `kabanero version` command to display the version of kabanero that is running.

----
kabanero version
----

=== Deactivate Kabanero

Run the `kabanero deactivate` command to prevent a collection from being shown to the development team, without deleting it.

----
kabanero deactivate collection-name
----

Running the deactivate command removes the specified collection from the list of available application types, without deleting it from the Kabanero instance.

This command is useful when you clone a collection and customize it for your business needs. Deactivation keeps the base collection in the app hub. The base collection continues to be updated and the updates percolate up to your cloned collection. To restore a deactivated collection, run the `kabanero refresh` command. See <<Refresh collections>>.

=== Log out of Kabanero

Run the `kabanero logout` command to disconnect from the Kabanero instance.

----
kabanero logout
----

== Options

=== Global options
These options can be enabled on any Kabanero command.


|===
|||
|-h
|--help
|help for kabanero
|`-v`
|`--verbose`
|Turns on debug output and logging to a file in $HOME/.kabanero/logs
|===

=== Login Options
Use these options with the `kabanero login` command.

|===
|||
|-h
|--help
|help for login
|`-p`
|`--password string`
|GitHub password or personal access token
|`-u`
|`--username string`
|GitHub user name
