:page-layout: general-reference
:page-doc-category: Getting Started
:page-title: Scripted Kabanero Foundation Setup
:linkattrs:

Today, Kabanero has been tested on the Origin Community Distribution of Kubernetes(OKD) version 3.11. There is intent to also expand testing on additional distributions including upstream Kubernetes in the future.

=== Prerequisites
* Kubernetes is installed
* openshift_master_default_subdomain is configured
** See https://docs.okd.io/3.11/install/configuring_inventory_file.html[Configuring Your Inventory File, window="_blank"]
* Wildcard DNS is available for your subdomain
** alternatively, nip.io can be used
* The Internal Registry is configured
** See more about the https://docs.okd.io/3.11/install_config/registry/index.html[Internal Registry, window="_blank"]


=== Installation Scripts

Retrieve the https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts[installation scripts from our kabanero-foundation repository, window="_blank"]


=== Installation

As a `cluster-admin`, run the following
....
openshift_master_default_subdomain=my.openshift.master.default.subdomain ./install-kabanero-foundation.sh
....



=== Sample Appsody project with manual Tekton pipeline run

Create a Persistent Volume for the pipeline to use. A sample hostPath `pv.yaml` is provided.
....
oc apply -f pv.yaml
....

Create the pipeline and execute the example manual pipeline run
....
APP_REPO=https://github.com/dacleyra/appsody-hello-world/ ./appsody-tekton-example-manual-run.sh
....

By default, the application container image will be built and pushed to the Internal Registry, and then deployed as a Knative Service.

Access application at `http://appsody-hello-world.appsody-project.my.openshift.master.default.subdomain`

If you need to access pipeline logs or make detailed pipeline changes, see below.

View manual pipeline logs
....
oc logs $(oc get pods -l tekton.dev/pipelineRun=appsody-manual-pipeline-run --output=jsonpath={.items[0].metadata.name}) --all-containers
....

Access Tekton dashboard 
`http://tekton-dashboard.my.openshift.master.default.subdomain`

The user <userid> should have the `tekton-dashboard-minimal` role in order to access the pipeline information:

```
oc policy add-role-to-user tekton-dashboard-minimal <userid>
```
