:page-layout: general-reference
:page-type: general
:page-title: Scripted Kabanero Foundation Setup
:linkattrs:

Today, Kabanero has been tested on the Origin Community Distribution of Kubernetes(OKD) version 3.11. There is intent to also expand testing on upstream Kubernetes in the future.

=== Prerequisites
* Kubernetes is installed
* The Kabanero Foundation is installed in a Kubernetes cluster
* openshift_master_default_subdomain is configured
** See https://docs.okd.io/3.11/install/configuring_inventory_file.html[Configuring Your Inventory File, window="_blank"]
* Wildcard DNS is available for your subdomain
** alternatively, nip.io can be used
* The Integrated Container Image Registry is configured
** See more about the https://docs.okd.io/3.11/install_config/registry/index.html[Internal Registry, window="_blank"]


=== Installation Scripts

Retrieve the https://github.com/kabanero-io/docs/tree/master/ref/scripts[installation scripts from our documentation repository, window="_blank"]


=== Installation

As an OKD `cluster-admin`, run the following
....
openshift_master_default_subdomain=my.openshift.master.default.subdomain ./install-kabanero-foundation.sh
....



=== Sample Appsody project with manual Tekton pipeline run

Create a Persistent Volume for the pipeline to use. A sample hostPath `pv.yaml` is provided.
....
oc apply -f pv.yaml
....

Create the pipeline and execute the example manual pipeline run
....
APP_REPO=https://github.com/dacleyra/appsody-hello-world/ ./appsody-tekton-example-manual-run.sh
....

By default, the application container image will be built and pushed to the Integrated Container Image Registry, and then deployed as a Knative Service.

View manual pipeline logs
....
oc logs $(oc get pods -l tekton.dev/pipelineRun=appsody-manual-pipeline-run --output=jsonpath={.items[0].metadata.name}) --all-containers
....

Access Tekton dashboard at `http://tekton-dashboard.my.openshift.master.default.subdomain`

Access application at `http://appsody-hello-world.appsody-project.my.openshift.master.default.subdomain`