:page-layout: doc
:page-doc-category: Configuration
:page-title: Connecting Kabanero to GitHub with Tekton Webhooks
:sectanchors:
= Connecting Kabanero to GitHub with Tekton Webhooks

A webhook is an outbound HTTP request that helps you create a relationship between your GitHub repository and a particular URL, in this case a https://github.com/kabanero-io/kabanero-pipelines/tree/Readme-updates#kabanero-pipelines[Tekton pipeline, window="_blank"]. After you configure the webhook, changes you make in your GitHub repository will trigger the Tekton pipeline and its associated tasks.

== Prerequisites

* A GitHub repository
* https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts[Kabanero Foundation, window="_blank"] or Kabanero Enterprise.
** Your Kabanero installation includes an instance of  the https://github.com/tektoncd/dashboard#installing-the-latest-release[Tekton Dashboard, window="_blank"] with the https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/InstallReleaseBuild.md[Webhooks Extension, window="_blank"] installed.

== Create a persistent volume
Tekton pipelines need a persistent volume. If there is no network storage available, create a `hostPath pv`. For more information, see https://github.com/kabanero-io/kabanero-pipelines/tree/Readme-updates#create-a-persistent-volume[Creating a persistent volume, window="_blank"].

== Generate a GitHub access token.
You need to generate a GitHub personal access token to use for creating the webhook and for accessing the repository source code during PipelineRuns. To generate the token:

. Go to https://github.com/settings/tokens[github.com/settings/tokens, window="_blank"] and click `Generate new token`.
. Check the `admin:repo_hook` option and click `Generate token`. If you are working in a private repository, more options might be required. Check with your administrator for details. *Make sure to save the token to a file since you can't see it after you leave this page.*

== Create secrets.
If you are working with a private or enterprise GitHub repository, you need to store your access token in a Kubernetes secret. If you are working with a public GitHub repository, you do not need to create a secret for your Tekton dashboard webhook.

. From your Tekton Dashboard, select `Secrets` from the sidebar menu and click `Add Secret`.
. Give your secret a unique name.
. For the `Namespace`, select `kabanero` from the drop-down list.
. For `Access To:`, select `Git Server` from the drop-down list.
. Enter your GitHub username and the personal access token you generated in the previous section.
. Select the service account that is used by the pipeline you want to trigger. For more information, see <<#serviceaccount, Service account>>.

If you want to push the image to Docker Hub, you need to create a separate secret to connect to Docker Hub. Follow the same procedure but use your Docker Hub username and password. For `Access To:`, select `Docker Registry` from the drop-down list.

== Create a webhook.
. From your Tekton Dashboard, select `webhooks` from the sidebar menu and click `Add Webhook`.
. Enter your information in the `Create Webhook` window.
+
Name::
Give your webhook a distinctive name.

Repository URL::
The URL of the GitHub repository that you want to connect to Kabanero.

Access token::
Use this field to create a secret to store your GitHub personal access token. Even if you already created a token-based Git secret from your Tekton Dashboard, you must also store your GitHub personal access token in this field. Click the green plus icon beside the field to open the `Create Access Token Secret` window.
+
Give your access token secret a descriptive name. In the `Access token` field, enter the GitHub personal access token that you previously generated in the *Generate a GitHub access token* step.

Namespace::
Select the Kubernetes namespace in which you want to run your pipeline. In this case, choose `kabanero`.

Pipeline::
Select the Pipeline in your target Namespace. PipelineRuns (and their accompanying PipelineResources) are created in this namespace. For more information, see https://github.com/kabanero-io/kabanero-pipelines/tree/Readme-updates#kabanero-pipelines[Kabanero Pipelines, window="_blank"].
,
[#serviceaccount]
Service Account::
This field specifies the service account that is used by the PipelineRun. OpenShift provides a `pipeline` service account, which has permissions to build and push an image. This service account can be used with simple pipelines. Alternatively, you can create a custom service account that is configured for whatever pipeline that you are running. For an example of a custom service account, see the `sample-pipeline-sa.yaml` file in the link:https://github.com/kabanero-io/kabanero-pipelines/tree/master/pipelines/common[Kabanero pipelines repo].

Docker registry::
Select the Docker registry where any built images are pushed. Use the same Docker registry that you created a secret for previously. For Docker Hub, use `index.docker.io/<docker_id>`. For an internal registry, use `docker-registry.default.svc:5000/kabanero`. If the namespace that is associated with your internal registry is not `kabanero`, use  `docker-registry.default.svc:5000/your-namespace`.

. After you complete the necessary information, click `Create`.

== Confirm your webhook.

. Look for the webhook in your GitHub Repository.
* From your GitHub repository, go to the `settings` tab and select `Webhooks` from the sidebar menu. Look for the webhook you created. Sometimes the webhook initially shows a 504 error icon but after the webhook is used it changes to a green check mark.

. Update code and merge a PR.
* Make any update to your code, create a PR, and merge it. This change kicks off a PipelineRun.

. Check the PipelineRun from your Tekton Dashboard.
* From your Tekton Dashboard, select `PipelineRuns` from the sidebar menu. Look for the PipelineRun you just kicked off.

Your GitHub repo is connected to Kabanero with a webhook. Changes in your code can now automatically trigger tasks that are specified by the pipeline.
