:page-layout: general-reference
:page-doc-category: Configuration
:page-title: Connecting Tekton to GitHub

= Connecting Tekton to GitHub

== Set up GitHub
If you haven't already, create a new GitHub repo for the desired project and have the code pushed to the GitHub repo. Copy the url of the GitHub repo as you will need that later. You will also need to create an Auth Token with webhook permissions: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line 

== Connect Tekton to GitHub

Now we can create a webhook. From the Tekton Dashboard, under "Extensions" in the left column, select webhooks-extension. Fill out the relevant information. In the access token section, you will need to use the `+` button and create a secret with the GitHub Auth token.  
*NOTE:* The `Name` field is used as part of the webhook callback URI. Therefore, the name must consist of valid URI characters.

You can check to see if it was created correctly by going into your GitHub repo and, in the settings->webhooks tab, you should see a webhook with a green checkmark. 

You can now change some code in your local repo, commit and push to GitHub to see Tekton kick off a pipeline run.