:page-layout: doc
:page-doc-category: Reference
:linkattrs:
:sectanchors:
= Troubleshooting

Learn how to isolate and resolve problems with Kabanero.

Make sure that your issues are not related to the operating system, such as disk, memory, and CPU capacities.

* See https://github.com/kabanero-io/kabanero-foundation#cluster-hardware-capacity[Kabanero resource requirements, window="_blank"]

== Using MustGather scripts to collect environment data

You can use the `mustgather` command to collect data about your environment.  This information can be useful in troubleshooting and fixing problems.

There are several MustGather scripts available:
  * `appsody-mustgather.sh`
  * `che-mustgather.sh`
  * `istio-mustgather.sh`
  * `kabanero-mustgather.sh`
  * `k`appnav-mustgather.sh`
  * `knative-mustgather.sh`
  * `mustgather-all.sh`
  * `tekton-mustgather.sh`

To run a MustGather script:

1. In a terminal session, navigate to the location where you cloned the kabanero-foundation repository.

2. Log in to your cluster.

  ```bash
  oc login https://<your_cluster_hostname> -u <username> -p <password>
  ```

3. Run a `mustgather` command.

For example:
  ```bash
  mustgather-all.sh
  ```

  **Tip**: You can set the environment variable `LOGS_DIR` to specify the data output location:
  ```bash
  LOGS_DIR=<my_directory> ./mustgather-all.sh
  ```
  {:tip}

  By default, MustGather data is stored in the `kabanero-debug` directory. The command also stores compressed information in the `kabaner-debug-<timestamp>.tar.gz` file.

== Errors when using a Tekton webhook to trigger pipelines

When using a Tekton webhook to trigger pipelines installed with Kabanero, the last task is the `monitor-result-task`, which may fail in some cases.
This might also cause the webhook pod to be in the "Error" state. The following failures of `monitor-result-task` in the TaskRun view can be disregarded
at this time; they do not impact the application deployment:

* `error creating GitHub client: error parsing PR number: pulls`
* `IOError: [Errno 2] No such file or directory: '/workspace/pull-request/pr.json'`


== `docker push` fails with gateway timeout error

When using OpenShift Container Platform on a cloud with Kubernetes service and an internal Docker registry, performing a `docker push` into the internal Docker
registry might result in a gateway time-out error.  This happens in cases where the input-output operations per second (IOPS) setting for the backing storage
of the registry's persistent volume (PV) is too low.

To resolve this problem, change the IOPS setting of the PV's backing storage device.
