:page-layout: doc
:page-doc-category: Configuration
:page-title: Configuring Kabanero CLI service authorization
:linkattrs:
:sectanchors:
:page-doc-number: 4.0
= Configuring Kabanero CLI service authorization

You can modify your Kabanero CR instance to provide authorization to the teams in GitHub that will administer the application stacks.
If you do not already have a team defined, see link:https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-team[Creating a team, window=_blank].

optional: Authorization setup If the container registry containing the stack images is protected, see link:https://github.com/kabanero-io/docs/blob/davco01a-patch-1/ref/general/configuration/stack-governance.adoc#the-governance-policy-is-specified-on-the-kabanero-cr-instance[See Step 2, window=_blank].

optional: Authorization setup if accessing repositories on Git Hub Enterprise, see link:https://kabanero.io/docs/ref/general/configuration/ghe-credentials.html[See Steps 1 and 2, window=_blank].  Step 4 explains how to set up the Kabanero Custom Resource document to point to your GHE repositories.


.To provide Login authorization to the CLI service:
* The `Spec.Github.organization` attribute should be set to the organization hosting the stacks in the remote GitHub repository.  In the previous example, the organization name is `my_org`.
* The `Spec.Github.teams` attribute should be set to a yaml list of GitHub teams in the remote GitHub repository, whose members can administer the stack using the stack management CLI.
* The `Spec.Github.apiUrl` attribute should be set to the API URL for the remote GitHub repository being used.  For example, the API URL for `github.com` is `https://api.github.com`.
+
A modified Kabanero CR instance for an application stack repository located in the `my_org` organization of the `github.example.com` GitHub repository using release `0.6.0` of stacks might look like this:
+
```yaml
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
  namespace: kabanero
spec:
  stacks:
    repositories:
    - name: custom
      https:
        url: https://github.example.com/my_org/stacks/releases/download/0.6.0/incubator-index.yaml
  github:
    organization: my_org
    teams:
      - stack-admins
      - admins
    apiUrl: https://api.github.com
```

Note: Avoid using the OpenShift Console to edit the Kabanero CR instance.  The console may change the `apiVersion` of the Kabanero CR instance from `v1alpha2` to `v1alpha1`.  There is a description of the issue link:https://github.com/openshift/console/issues/4444[here].
