:page-layout: doc
:page-doc-category: Configuration
:page-title: Configuring Kabanero CLI service authorization
:linkattrs:
:sectanchors:
:page-doc-number: 4.0
= Configuring Kabanero CLI service authorization

You can modify your Kabanero CR instance to provide authorization to the teams in GitHub that will administer the collection(s).
If you do not already have a team defined, see link:https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-team[Creating a team, window=_blank].

.To provide authorization:
* The `Spec.Github.organization` attribute should be set to the organization hosting the collections in the remote GitHub repository.  In the example above, the organization name is `my_org`.
* The `Spec.Github.teams` attribute should be set to a yaml list of GitHub teams in the remote GitHub repository, whose members can administer the collection using the Kabanero CLI.
* The `Spec.Github.apiurl` attribute should be set to the API URL for the remote GitHub repository being used.  For example, the API URL for `github.com` is `api.github.com`.
+
A modified Kabanero CR instance for a collection repository located in the `my_org` organization of the `github.example.com` GitHub repository using release `0.3.0` of collections might look like this:
+
```yaml
apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
  namespace: kabanero
spec:
  collections:
    repositories:
    - name: custom
      url: https://github.example.com/my_org/collections/releases/download/0.3.0/kabanero-index.yaml
      activateDefaultCollections: true
  github:
    organization: my_org
    teams:
      - collection-admins
      - admins
    apiurl: api.github.com
```
