:page-layout: doc
:page-doc-category: Configuration
:page-title: Configuring Governance Policy for Stacks
:linkattrs:
:sectanchors:
= Configuring Governance Policy for Stacks

Kabanero can help detect when there is a discrepency between the stack that an application wants to build with, and the set of stacks that have been configured in the Kabanero instance.  Kabanero uses the digest of the container images to enforce the policy.

There are four permitted stack governance policies:

. `strictDigest` - The digest of the stack image used by the application must match the digest of a container image which is currently active in the Kabanero instance.

. `activeDigest` - The `MAJOR.MINOR` stack image version will be used to find a suitable container image which is currently active in the Kabanero instance.  If a suitable image is found, the build will proceed with that image.

. `ignoreDigest` - The tags of the stack image used by the application must match the tags of a container image which is currently active in the Kabanero instance.  The digest of the stack image is ignored.

. `none` - Disables any digest or tag based image validation.

The governance policy is specified on the Kabanero CR instance:

. Modify your Kabanero CR instance to specify the stack governance policy.  The policy information is specified in the `spec.governancePolicy.stackPolicy` field of the Kabanero CR instance.  One of the four policies mentioned previously should be specified here.  For example, the `activeDigest` policy is specified as follows:
+
```yaml
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
  namespace: kabanero
spec:
  governancePolicy:
    stackPolicy: activeDigest
```
===
. If the container registry containing the stack images is protected, a secret must be created which contains the credentials necessary to authenticate with the container registry.  The secret should contain both `username` and `password` keys in the `data` section. The value of `password` can be either a password or a PAT.  The secret must also contain an annotation which associates it with the hostname where the container registry exists.  The format of the annotation is `kabanero.io/docker-0: https://hostname` where `hostname` is replaced with the container registry hostname.  For example, the following yaml defines a secret that is used to access a Docker Hub registry:
+
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    kabanero.io/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
  username: myUserName
  password: <PAT>
```
+
For more information about how Kabanero uses this secret, read the notes at the end of this page.

=== Notes about credential selection

In the event that the same credentials should be used for more than one container registry, multiple annotations can be added to the secret.  For example, if the same username and password should be used for both `my.registry.com` and `fred.registry.com`, the following annotations are valid:

```yaml
metadata:
  name: basic-user-pass
  annotations:
    kabanero.io/docker-0: https://my.registry.com
    kabanero.io/docker-1: https://fred.registry.com
```

If more than one Secret matches a given hostname, the one with the lexically lowest key (kabanero.io/docker-*) is used.

Note that although the annotation contains the word `docker`, it applies to all supported container registries.

== Need help?
If you have questions, we would like to hear from you.
You can reach out to the community for assistance on the https://ibm-cloud-tech.slack.com/messages/CJZCYTD0Q[Kabanero Slack channel, window="_blank"].
