:page-layout: doc
:page-doc-category: Installation
:page-title: Uninstalling Kabanero Foundation
:linkattrs:
:page-doc-number: 2.0
:sectanchors:

== Uninstalling Kabanero Foundation

A sample uninstall script is available in the kabanero-operator GitHub repository.  This script will perform the reverse of the `install.sh` script. Before running the `uninstall.sh` script, consider removing any resources that were not created by the 'install-kabanero-foundation' script, such as webhooks, serverless services, or applications.

The sample uninstallation script will completely remove all dependencies from the cluster, including serverless, pipelines, and service mesh.  You can modify your local copy of the script if desired.

== Uninstallation

. Obtain the uninstallation script for the release of Kabanero that you want to uninstall.
* `curl -s -O -L https://github.com/kabanero-io/kabanero-operator/releases/download/0.9.0/uninstall.sh`

. As a `cluster-admin`, execute the sample uninstallation script:
+
----
./uninstall.sh
----
